---
title: "Developer guide: Writing a data wrapper class"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Developer guide: Writing a data wrapper class}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The following is a guide for development of wrapper classes for single-cell data structures.
For this guide, we will focus on writing a wrapper class for Seurat objects which supports the `cells`, `cell-sets`, and `expression-matrix` Vitessce data types.

To begin, we can write a skeleton for the class, which contains functions that we will fill in.
Here, we start by overriding the `get_cells`, `get_cell_sets`, and `get_expression_matrix` of the parent `AbstractWrapper` class.

The `initialize` constructor function currently takes one parameter `obj` which will be the Seurat of interest (i.e., the object that we are wrapping).

```r
SeuratWrapper <- R6::R6Class("SeuratWrapper",
  inherit = AbstractWrapper,
  public = list(
    obj = NULL,
    initialize = function(obj) {
      self$obj <- obj
    },
    get_cells = function(port, dataset_uid, obj_i) {
        # TODO
    },
    get_cell_sets = function(port, dataset_uid, obj_i) {
        # TODO
    },
    get_expression_matrix = function(port, dataset_uid, obj_i) {
        # TODO
    }
  )
)
```

## Cells

We can begin to fill in the `get_cells` function corresponding to the `cells` data type.
Files with the `cells` data type can contain cell-level observations, such as dimensionality reduction coordinates for each cell.

For now, we can create a new function called `create_cells_list` which we will fill in later.

The return value for all functions with the `get_` prefix should be a list with two named values:

- `routes`: a list containing `VitessceConfigServerRoute` objects, and
- `file_defs`: a list containing file definitions.

File definitions should be lists with named values:

- `type`: a Vitessce data type string (for convenience, the values in the `DataType` list can be used),
- `fileType`: a Vitessce file type string (for convenience, the values in the `FileType` list can be used),
- `url`: a URL string (required for most file types, but optional for the `raster.json` file type),
- `options`: optional list of extra options (not necessary for any JSON file types).

The `VitessceConfigServerRoute` constructor takes two parameters:

- a path for the route (such as `/cells` which will become `http://localhost:8000/cells` if the web server is on port 8000), and
- the data to serve on the route (such as an R list which will be automatically converted to a JSON object).

For convenience, the functions `super$get_route` and `super$get_url` can be used to create the route and URL strings.
For example, `/cells` and `http://localhost:8000/cells`, respectively.

The final line of the function `retval` will result in `retval` being the return value of the function.

```r
SeuratWrapper <- R6::R6Class("SeuratWrapper",
  inherit = AbstractWrapper,
  public = list(
    obj = NULL,
    initialize = function(obj) {
      self$obj <- obj
    },
    create_cells_list = function() {
        # TODO
    },
    get_cells = function(port, dataset_uid, obj_i) {
        retval <- list(
            routes = list(),
            file_defs = list()
        )

        cells_list <- self$create_cells_list()

        retval$routes <- list(
            VitessceConfigServerRoute$new(
                super$get_route(dataset_uid, obj_i, "cells"),
                super$create_response_json(cells_list)
            )
        )
        retval$file_defs <- list(
            list(
                type = DataType$CELLS,
                fileType = FileType$CELLS_JSON,
                url = super$get_url(port, dataset_uid, obj_i, "cells")
            )
        )
        retval
    },
    get_cell_sets = function(port, dataset_uid, obj_i) {
        # TODO
    },
    get_expression_matrix = function(port, dataset_uid, obj_i) {
        # TODO
    }
  )
)
```

Next, we want to fill in the `create_cells_list` function.
This function should return an R list which will be automatically converted to a JSON object by [jsonlite](https://cran.r-project.org/web/packages/jsonlite/vignettes/json-aaquickstart.html).

For reference:

- [`cells.json` schema](https://github.com/vitessce/vitessce/blob/master/src/schemas/cells.schema.json)
- [`cells.json` small example](https://github.com/vitessce/vitessce/blob/master/src/schemas/fixtures/cells.good.json)
- [`cells.json` full example](https://s3.amazonaws.com/vitessce-data/0.0.31/master_release/dries/dries.cells.json)

We know that we need to obtain the following from the Seurat object:

- a unique ID for each cell, and
- an (x, y) scatterplot coordinate representing the first two dimensions of a dimensionality reduction for each cell.

When we inspect a Seurat object in the R environment, we can see that it has the type `S4 object of class Seurat`.

To access the values in an S4 object, we can use `slot(obj, "key")` where `"key"` is replaced by the key for the part of the object that we want to access.

Inspecting the object further, we can see that:

- dimensionality reductions are stored under the key `"reductions"`
- cell barcodes are stored under the key `"active.ident"`

To generalize our function, we can get a list of names of each dimensionality reduction available with `names(slot(obj, "reductions"))`.

We can get a list of cell IDs with `names(slot(obj, "active.ident"))`.

Then we can iterate over the cell IDs and set up a new empty object with `obj_list()`.
Note [`obj_list()`](https://github.com/vitessce/vitessce-r/blob/8d4d7f9/R/helpers.R#L35) returns an empty R list that is always translated to a JSON object (rather than the base R `list()` which is translated to a JSON _array_ when empty).

Then we can iterate over each available dimensionality reduction and cell.
We obtain the cell's (x,y) coordinates with `embedding_matrix[cell_id, 1:2]` where `embedding_matrix` is the dimensionality reduction matrix.
For example, if the dimensionality reduction is `"pca"` then the matrix can be accessed at `slot(slot(obj, "reductions")[["pca"]], "cell.embeddings")`.

Finally, we return the R list we created.

```r
SeuratWrapper <- R6::R6Class("SeuratWrapper",
  inherit = AbstractWrapper,
  public = list(
    obj = NULL,
    initialize = function(obj) {
      self$obj <- obj
    },
    create_cells_list = function() {
        obj <- self$obj
        embeddings <- slot(obj, "reductions")
        available_embeddings <- names(embeddings)

        cell_ids <- names(slot(obj, "active.ident"))
        cells_list <- obj_list()
        for(cell_id in cell_ids) {
            cells_list[[cell_id]] <- list(
                mappings = obj_list()
            )
        }
        for(embedding_name in available_embeddings) {
            embedding <- embeddings[[embedding_name]]
            embedding_matrix <- slot(embedding, "cell.embeddings")
            for(cell_id in cell_ids) {
                cells_list[[cell_id]]$mappings[[embedding_name]] <- unname(embedding_matrix[cell_id, 1:2])
            }
        }

        cells_list
    },
    get_cells = function(port, dataset_uid, obj_i) {
        # omitted
    },
    get_cell_sets = function(port, dataset_uid, obj_i) {
        # TODO
    },
    get_expression_matrix = function(port, dataset_uid, obj_i) {
        # TODO
    }
  )
)
```

Putting it all together:

```r
#' Seurat object wrapper class
#' @title SeuratWrapper Class
#' @docType class
#' @description
#' Class representing a local Seurat object in a Vitessce dataset.
#'
#' @rdname SeuratWrapper
#' @export
SeuratWrapper <- R6::R6Class("SeuratWrapper",
  inherit = AbstractWrapper,
  public = list(
    #' @field obj The object to wrap.
    #' @keywords internal
    obj = NULL,
    #' @description
    #' Create a wrapper around a Seurat object.
    #' @param obj The object to wrap.
    #' @return A new `SeuratWrapper` object.
    initialize = function(obj) {
      self$obj <- obj
    },
    #' @description
    #' Create a list representing the cells in the Seurat object.
    #' @return A list that can be converted to JSON.
    #' @keywords internal
    create_cells_list = function() {
        obj <- self$obj
        embeddings <- slot(obj, "reductions")
        available_embeddings <- names(embeddings)

        cell_ids <- names(slot(obj, "active.ident"))
        cells_list <- obj_list()
        for(cell_id in cell_ids) {
            cells_list[[cell_id]] <- list(
                mappings = obj_list()
            )
        }
        for(embedding_name in available_embeddings) {
            embedding <- embeddings[[embedding_name]]
            embedding_matrix <- slot(embedding, "cell.embeddings")
            for(cell_id in cell_ids) {
                cells_list[[cell_id]]$mappings[[embedding_name]] <- unname(embedding_matrix[cell_id, 1:2])
            }
        }

        cells_list
    },
    #' @description
    #' Get the routes and file definitions for the cells data type.
    #' @param port The port on which the web server is serving.
    #' @param dataset_uid The ID for this dataset.
    #' @param obj_i The index of this data object within the dataset.
    #' @return A list of `routes` and `file_defs` lists.
    get_cells = function(port, dataset_uid, obj_i) {
        retval <- list(
            routes = list(),
            file_defs = list()
        )

        cells_list <- self$create_cells_list()

        retval$routes <- list(
            VitessceConfigServerRoute$new(
                super$get_route(dataset_uid, obj_i, "cells"),
                super$create_response_json(cells_list)
            )
        )
        retval$file_defs <- list(
            list(
                type = DataType$CELLS,
                fileType = FileType$CELLS_JSON,
                url = super$get_url(port, dataset_uid, obj_i, "cells")
            )
        )
        retval
    },
    get_cell_sets = function(port, dataset_uid, obj_i) {
        # TODO
    },
    get_expression_matrix = function(port, dataset_uid, obj_i) {
        # TODO
    }
  )
)
```

## Cell sets

TO DO

## Expression matrix

TO DO