---
title: "Overview: Using the widget with local data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview: Using the widget with local data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The main goal of this R package is to enable configuring Vitessce visualizations using R syntax.

We also aim to simplify the data conversion process by providing [dataset wrapper classes](https://vitessce.github.io/vitessce-r/reference/index.html#section-dataset-wrapper-classes) that automatically convert common single-cell data structures to [file formats supported by Vitessce](http://vitessce.io/docs/data-types-file-types/).

Our effort to develop converters for R formats remains ongoing. However, we provide a guide for R developers to [write data conversion functions](https://vitessce.github.io/vitessce-r/articles/dev_wrapper_class.html) to support any type of R single-cell data structure (or to improve conversion for already-supported data structures).

The following vignettes in the "Examples with Local Data" section demonstrate how the dataset wrapper classes can be used with relatively small single-cell datasets stored on your local machine.

Please note that due to a [lack of native R support for Zarr](https://github.com/vitessce/vitessce-r/issues/7), the R dataset conversion functions are currently slow and convert to uncompressed JSON files. 
If you aim to visualize a large dataset (thousands of cells and genes) in Vitessce, we suggest using Zarr. 

In the Vitessce Python package, the [AnnDataWrapper](https://vitessce.github.io/vitessce-python/api_data.html#vitessce.wrappers.AnnDataWrapper) class automatically converts AnnData objects to Zarr stores. Alternatively, you may convert your data structure to a Zarr store manually using any [Zarr implementation](https://github.com/zarr-developers/zarr_implementations), and manually [specify the Zarr store paths](http://vitessce.io/docs/data-file-types/#anndata-as-zarr) in the Vitessce configuration.

Feel free to subscribe to the [Zarr in R issue](https://github.com/vitessce/vitessce-r/issues/7) for future updates about Zarr support in the Vitessce R package.
